import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const delegate = _AppLocalizationsDelegate();

  static const _values = <String, Map<String, String>>{
    'en': {
      'home': 'Home',
      'downloads': 'Downloads',
      'batch': 'Batch',
      'settings': 'Settings',
      'skip': 'Skip',
      'continue': 'Continue',
      'next': 'Next',
      'back': 'Back',
      'close': 'Close',
      'getStarted': 'Get Started',
      'onboardingTitle1': 'Paste any supported media link',
      'onboardingDesc1':
          'Copy a public video link from your favorite platform and paste it here.',
      'onboardingTitle2': 'Choose your format',
      'onboardingDesc2':
          'Download video, extract audio, save thumbnails, and more.',
      'onboardingTitle3': 'Go Premium for more power',
      'onboardingDesc3':
          'Unlock FHD & 4K quality, no watermark when available, batch downloads, Quick Editor, Audio Swap, faster queue, and no ads.',
      'pasteYourVideoLink': 'Paste your video link',
      'howToUse': 'How to use',
      'analyzeLink': 'Analyze link',
      'downloadCompleted': 'Download completed',
      'downloadSavedToLibrary': 'Download saved to your library.',
      'analyzeFailed': 'Could not analyze this link. Please try again.',
      'backendUnavailableDemo': 'Backend unavailable. Showing demo result.',
      'downloadJobCreated': 'Download job created.',
      'downloadJobFailed': 'Could not create download job. Please try again.',
      'downloadFailed': 'Download failed. Please try another format or link.',
      'downloadFailedNoFiles':
          'Download completed, but no files were returned.',
      'noMediaToShow': 'No media to show',
      'analyzeFirstForOptions':
          'Paste and analyze a link first to choose download options.',
      'noDownloadInProgress': 'No download in progress',
      'startDownloadFirst': 'Start a download from the options screen first.',
      'noVideoSelected': 'No video selected',
      'openQuickEditorFirst':
          'Open Quick Editor from a downloaded video first.',
      'instagramBlocked':
          'Instagram blocked this request. Please refresh Instagram cookies and try again.',
      'facebookPhotoUnavailable':
          'Facebook photo posts are not available for this link. Try a video link.',
      'youtubeRequiresAuth':
          'YouTube requires sign-in verification. Please refresh YouTube cookies from the admin panel.',
      'youtubeFormatUnavailable':
          'This YouTube format is not available. Try another quality or link.',
      'youtubeFormatsTemporarilyUnavailable':
          'YouTube video formats are temporarily unavailable. Please try another link.',
      'connectionProblem': 'Connection problem. Please try again.',
      'serverConnectionProblem':
          'Could not connect to the server. Please check your internet connection and try again.',
      'queued': 'Queued',
      'downloading': 'Downloading',
      'readyToOpen': 'Ready to open',
      'preparingYourFile': 'Preparing your file',
      'preparingYourFileDescription':
          'Saving and preparing the file on your device before actions become available.',
      'savingToDevice': 'Saving to your device',
      'savingFileToDevice': 'Saving file to your device...',
      'downloadSaveFailed':
          'The download completed, but the file could not be saved on your device. Please try again.',
      'addingToGallery': 'Adding to Gallery',
      'galleryPublishFailed':
          'File saved in ApexLoad, but it could not be added to Gallery.',
      'calculating': 'Calculating...',
      'selectDownloadOption': 'Please select at least one download option.',
      'upgradeToPremium': 'Upgrade to Premium',
      'premium': 'Premium',
      'premiumRequired': 'Premium required',
      'legalShort': 'Only download content you own or have permission to use.',
      'legalFull':
          'This app is intended only for downloading content you own, have permission to use, or content that is publicly allowed to be downloaded. Users are responsible for respecting copyright and platform terms.',
      'supportedPlatforms': 'Supported platforms',
      'recentDownloads': 'Recent downloads',
      'viewAll': 'View all',
      'pasteFirst': 'Paste a public media link first.',
      'clipboardEmpty': 'Clipboard is empty right now.',
      'premiumActive': 'Premium active',
      'active': 'Active',
      'freePlan': 'Free plan',
      'noWatermarkDownloads': 'No watermark downloads',
      'noWatermarkWhenAvailable': 'No watermark when available',
      'homeUpgradeCopy':
          'Go Premium for FHD & 4K downloads, no ads, batch downloads, Quick Editor, Audio Swap, and',
      'fhd4kDownloads': 'FHD & 4K downloads when available',
      'fhd4kDownloadsWhenAvailable': 'Download in FHD & 4K when available.',
      'fhd4kExport': 'FHD & 4K export',
      'fhd4kShort': 'FHD & 4K',
      'unlockFhd4kQuality': 'Unlock FHD & 4K quality',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'lifetime': 'Lifetime',
      'monthlyPrice': r'$0.99/month',
      'yearlyPrice': r'$9.99/year',
      'lifetimePrice': r'$24.99 one-time',
      'import': 'Import',
      'validate': 'Validate',
      'language': 'Language',
      'theme': 'Theme',
      'quickEditor': 'Quick Editor',
      'quickEditorSubtitle':
          'Trim, mute, extract audio, and compress your videos.',
      'quickEditorLandingSubtitle':
          'Choose a downloaded video or a local file, then pick a local editing tool.',
      'quickEditorPremiumTitle': 'Quick Editor is a Premium feature.',
      'quickEditorPremiumMessage':
          'Upgrade to trim, mute, extract audio, replace audio, and compress your videos.',
      'chooseVideoSource': 'Choose video source',
      'chooseVideoSourceDescription':
          'Use an ApexLoad download or pick a video stored on this device.',
      'chooseLocalVideo': 'Choose local video',
      'chooseFromDownloads': 'Choose from Downloads',
      'noEditableVideosYet':
          'No downloaded videos yet. Download a video first or choose a local file.',
      'localFile': 'Local file',
      'editVideo': 'Edit Video',
      'trimVideo': 'Trim video',
      'muteVideo': 'Mute video',
      'extractAudio': 'Extract audio',
      'compressVideo': 'Compress video',
      'videoOptimizer': 'Video Optimizer',
      'videoOptimizerSubtitle':
          'Reduce size, convert to MP4, and prepare a cleaner output locally.',
      'videoOptimizerPremiumTitle': 'Video Optimizer is a Premium feature.',
      'videoOptimizerPremiumMessage':
          'Upgrade to optimize videos locally before sharing.',
      'optimizerPreset': 'Optimizer preset',
      'optimizerLocalOnly': 'Optimization runs locally on this device.',
      'optimizeVideo': 'Optimize video',
      'optimizerSuccess': 'Video optimized successfully',
      'convertVideoToMp4': 'Convert Video to MP4',
      'exportEditedVideo': 'Export edited video',
      'format': 'Format',
      'startTime': 'Start time',
      'endTime': 'End time',
      'trimDuration': 'Trim duration',
      'seconds': 'seconds',
      'previewSelection': 'Preview selection',
      'validTrimRange': 'Please select a valid trim range.',
      'videoPreviewUnavailable':
          'Video preview is not available for this file.',
      'applyTrim': 'Apply Trim',
      'removeOriginalAudio': 'Remove original audio',
      'applyMute': 'Apply Mute',
      'standard': 'Standard',
      'high': 'High',
      'smallFile': 'Small file',
      'balanced': 'Balanced',
      'highQuality': 'High quality',
      'highestQuality': 'Highest quality',
      'estimatedReduction': 'Estimated size reduction: 35% smaller',
      'compress': 'Compress',
      'exportSettings': 'Export Settings',
      'saveToGallery': 'Save to gallery',
      'noWatermarkNote': 'Applied only when the platform/source provides it.',
      'processingLocally': 'Processing locally on this device',
      'processingEditor': 'Processing locally on this device',
      'trimSuccess': 'Trim applied successfully',
      'muteSuccess': 'Video muted successfully',
      'audioExtractedSuccess': 'Audio extracted successfully',
      'compressSuccess': 'Video compressed successfully',
      'exportSuccess': 'Edited video exported successfully',
      'couldNotEditFile':
          'Could not edit this file. Please try another file or option.',
      'originalFileMissing':
          'The original file could not be found. Please download it again and try editing.',
      'fileMustBeSavedBeforeEdit':
          'This file must be saved on your device before editing. Please download it again.',
      'savedToApexLoad': 'Saved to ApexLoad',
      'editedFileSavedSuccess': 'Edited file saved successfully.',
      'couldNotGenerateThumbnail': 'Could not generate thumbnail.',
      'deleteThisFile': 'Delete this file?',
      'fileDeleted': 'File deleted.',
      'sharingFailed': 'Sharing failed. Please try again.',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'older': 'Older',
      'edited': 'Edited',
      'editor': 'Editor',
      'editorToolSoon': 'This editor tool will be added soon.',
      'quickEditorBenefit': 'Trim, mute, extract audio, and compress videos.',
      'platformTikTok': 'TikTok',
      'platformInstagram': 'Instagram',
      'platformFacebook': 'Facebook',
      'platformXTwitter': 'X/Twitter',
      'platformYouTubeShorts': 'YouTube Shorts',
      'platformPinterest': 'Pinterest',
      'platformReddit': 'Reddit',
      'platformSnapchat': 'Snapchat',
      'unlockPremiumTitle': 'Unlock ApexLoad Premium',
      'premiumSubtitle': 'More speed. More quality. No limits.',
      'premiumDownloads': 'Premium Downloads',
      'premiumCreatorTools': 'Premium Creator Tools',
      'premiumEditorTools': 'Premium Editor Tools',
      'premiumUnlimitedDescription': 'Download without daily limits.',
      'premiumHdDownloads': 'HD / Full HD / 4K downloads',
      'premiumHdDownloadsDescription':
          'Higher quality downloads when the source provides them.',
      'premiumBatchDescription': 'Queue up to 5 links at a time.',
      'premiumMp3Extraction': 'MP3 audio extraction',
      'premiumMp3Description': 'Save audio from supported videos.',
      'premiumNoWatermark': 'No watermark when possible',
      'premiumNoWatermarkDescription':
          'Applied automatically when the source supports it.',
      'premiumQuickEditorTools': 'Quick Editor tools',
      'premiumFasterQueue': 'Faster processing queue',
      'premiumFasterQueueDescription': 'Priority handling for supported jobs.',
      'premiumNoAdsDescription': 'Use ApexLoad without ad interruptions.',
      'videoToGifBenefit':
          'Turn your favorite video moments into shareable GIFs.',
      'reelsShortsBenefit': 'Create platform-ready vertical videos in seconds.',
      'whatsappStatusBenefit': 'Save viewed WhatsApp photos and videos easily.',
      'videoOptimizerBenefit':
          'Reduce file size while controlling output quality.',
      'advancedAudioSwapBenefit': 'Choose exactly where your new audio begins.',
      'professionalTrimPreview': 'Professional Trim Preview',
      'audioStartSelector': 'Audio Start Selector',
      'advancedAudioSwap': 'Advanced Audio Swap',
      'localVideoConversion': 'Local video conversion',
      'localOptimization': 'Local optimization',
      'noAds': 'No ads',
      'batchDownloads': 'Batch downloads',
      'audioExtraction': 'Audio extraction',
      'fasterQueue': 'Faster queue',
      'unlimitedDownloads': 'Unlimited downloads',
      'cloudSave': 'Cloud save',
      'bestValue': 'Best Value',
      'premiumActivatedDemo': 'Premium activated for this demo.',
      'premiumActiveButton': 'Premium Active',
      'termsPrivacyPlaceholder':
          'Terms and Privacy are placeholders for this frontend version.',
      'downloadOptions': 'Download options',
      'chooseFormat': 'Choose format',
      'customFilename': 'Custom filename',
      'download': 'Download',
      'openAudioTool': 'Open audio extraction tool',
      'viewPremium': 'View Premium',
      'premiumOption': 'Premium option',
      'premiumFeatureSummary':
          'Unlock FHD & 4K quality, no watermark when available, Quick Editor, audio extraction, and batch downloads.',
      'downloadProgress': 'Download progress',
      'openLibrary': 'Open Library',
      'downloadAnother': 'Download Another',
      'cancel': 'Cancel',
      'platform': 'Platform',
      'speed': 'Speed',
      'queuePosition': 'Queue position',
      'savedLocally': 'Saved locally',
      'done': 'Done',
      'searchDownloads': 'Search downloads',
      'noDownloadsYet': 'No downloads yet',
      'pasteLinkOnHome': 'Paste a link on the Home screen to start.',
      'renameFile': 'Rename file',
      'filename': 'Filename',
      'save': 'Save',
      'upgradeNow': 'Upgrade Now',
      'maybeLater': 'Maybe Later',
      'dailyLimitReachedTitle': 'Daily limit reached',
      'dailyLimitReachedMessage':
          'You reached your free daily limit. Upgrade to Premium for unlimited downloads.',
      'freeDownloadsLeft': 'Free downloads left today: {count}/5',
      'adPlaceholderTitle': 'Ad Placeholder',
      'adPlaceholderMessage': 'This is where an ad will appear for free users.',
      'premiumActivatedSuccess': 'Premium activated successfully.',
      'premiumMonthly': 'Premium Monthly',
      'premiumYearly': 'Premium Yearly',
      'premiumLifetime': 'Premium Lifetime',
      'fhd4kPremiumTitle': 'FHD & 4K downloads are Premium.',
      'fhd4kPremiumMessage':
          'Upgrade to download in higher quality when available.',
      'batchPremiumTitle': 'Batch downloads are Premium.',
      'batchPremiumMessage': 'Upgrade to download multiple links together.',
      'audioExtractionPremiumTitle': 'Audio extraction is Premium.',
      'audioExtractionPremiumMessage':
          'Upgrade to extract audio from your media links.',
      'noWatermarkPremiumTitle': 'No watermark downloads are Premium.',
      'noWatermarkPremiumMessage':
          'Available when the platform provides a no-watermark version.',
      'audioSwapPremiumTitle': 'Audio Swap is a Premium feature.',
      'audioSwapPremiumMessage':
          'Upgrade to replace the original video sound with your own audio.',
      'audioSwap': 'Audio Swap',
      'audioSwapReplaceAudio': 'Audio Swap / Replace Audio',
      'replaceAudio': 'Replace Audio',
      'audioSwapSubtitle': 'Replace original audio with your own sound.',
      'audioSwapDescription':
          'Replace the original video sound with an audio file from your phone.',
      'chooseAudioFile': 'Choose audio file',
      'pickAudioFile': 'Pick Audio File',
      'selectedAudio': 'Selected audio',
      'audioFormatSupport': 'MP3 / M4A / WAV supported later',
      'audioStartPosition': 'Audio start position in video',
      'audioStartPoint': 'Audio start point',
      'audioStartPointHelp':
          'Choose where the selected audio begins. It will start at the beginning of the video.',
      'audioStartsAtVideoPoint':
          'The new audio starts at video second 0. If it is shorter than the video, choose whether to loop it or leave the rest silent.',
      'audioSectionUsed': 'Audio section used',
      'removeOriginalSound': 'Remove original sound',
      'keepOriginalSoundSoftly': 'Keep original sound softly',
      'audioVolume': 'Audio volume',
      'preview': 'Preview',
      'applyAudioSwap': 'Apply Audio Swap',
      'audioReplacedSuccess': 'Audio replaced successfully.',
      'couldNotReplaceAudio':
          'Could not replace the audio. Please try another audio file.',
      'noAudioSelected': 'Pick an audio file first.',
      'originalAudio': 'Original audio',
      'replaceOriginalAudio': 'Replace original audio',
      'removeOriginalAudioOnly': 'Remove original audio only',
      'chooseNewAudio': 'Choose new audio',
      'noNewAudioNeeded': 'No new audio needed for remove-only export.',
      'previewAndApply': 'Preview and apply',
      'previewWithNewAudio': 'Preview with new audio',
      'audioTrimmedToVideoLength':
          'The new audio will be trimmed to match the video length.',
      'audioShorterThanVideo':
          'If the audio is shorter, the export ends when the new audio ends.',
      'advancedOptions': 'Advanced options',
      'videoToGif': 'Video to GIF',
      'createGif': 'Create GIF',
      'previewGifRange': 'Preview GIF range',
      'gifCreatedSuccess': 'GIF created successfully.',
      'couldNotCreateGif': 'Could not create this GIF. Try a shorter range.',
      'videoToGifPremiumTitle': 'Video to GIF is a Premium feature.',
      'reelsShortsCreator': 'Reels/Shorts Creator',
      'createReelShort': 'Create Reel/Short',
      'chooseOutputFormat': 'Choose output format',
      'resizeMode': 'Resize mode',
      'smartCrop': 'Smart crop',
      'fitWithBlurredBackground': 'Fit with background',
      'fitWithSolidBackground': 'Fit with solid background',
      'centerCrop': 'Center crop',
      'reelShortCreatedSuccess': 'Reel/Short created successfully.',
      'couldNotCreateReelShort':
          'Could not create this Reel/Short. Please try another option.',
      'reelsShortsPremiumTitle': 'Reels/Shorts Creator is a Premium feature.',
      'chooseVideo': 'Choose video',
      'selectedVideo': 'Selected video',
      'gifSettings': 'GIF settings',
      'quality': 'Quality',
      'size': 'Size',
      'small': 'Small',
      'medium': 'Medium',
      'original': 'Original',
      'fps': 'FPS',
      'loop': 'Loop',
      'reelsShortsOutputNote': 'Exports locally in a social-friendly MP4 size.',
      'demoPreviewReady': 'Demo preview is ready.',
      'somethingWentWrong': 'Something went wrong. Please try again.',
      'demoActionForNow': '{action} is a demo action for now.',
      'sharingSoon': 'Sharing will be added soon.',
      'couldNotOpenFile': 'Could not open this file. Please try again.',
      'fileNoLongerAvailable':
          'This file is no longer available on your device.',
      'demoExtractionPrepared': 'Demo {format} extraction prepared.',
      'batchQueueCreated': 'Demo queue created. Backend will run this later.',
      'batchLimitExceeded': 'You can download up to 5 links at a time.',
      'notAvailableOnClip': 'Not available on this clip',
      'notAvailableForImage': 'Not available for this image',
      'Instagram photo posts are not available for this link. Try a Reel/video link.':
          'Instagram photo posts are not available for this link. Try a Reel/video link.',
      'Facebook photo posts are not available for this link. Try a video link.':
          'Facebook photo posts are not available for this link. Try a video link.',
      'noWatermarkApplied': 'No watermark applied when available',
      'downloadSelected': 'Download selected',
      'downloadSelectedItems': 'Download selected items',
      'downloadSelectedItemsCount': 'Download {count} selected items',
      'selectedItemsDownloaded': 'Selected items downloaded successfully',
      'chooseImageFormat': 'Choose image format',
      'originalImage': 'Original Image',
      'highQualityImage': 'High Quality Image',
      'compressedImage': 'Compressed Image',
      'jpgImage': 'JPG Image',
      'pngImage': 'PNG Image',
      'bestAvailableQuality': 'Best available quality',
      'premiumQualityWhenAvailable': 'Premium quality when available',
      'smallerFileSize': 'Smaller file size',
      'standardFormat': 'Standard format',
      'whenAvailable': 'When available',
      'imagePremiumTitle': 'High quality images are Premium.',
      'imagePremiumMessage':
          'Upgrade to download premium image formats when available.',
      'yourApexLoad': 'Your ApexLoad',
      'appStatus': 'App Status',
      'plan': 'Plan',
      'downloadsToday': 'Downloads today',
      'storageUsed': 'Storage used',
      'locked': 'Locked',
      'unlocked': 'Unlocked',
      'free': 'Free',
      'all': 'All',
      'video': 'Video',
      'audio': 'Audio',
      'images': 'Images',
      'open': 'Open',
      'share': 'Share',
      'edit': 'Edit',
      'rename': 'Rename',
      'delete': 'Delete',
      'goHome': 'Go Home',
      'pasteOneLinkPerLine': 'Paste one public link per line',
      'queuePreview': 'Queue preview',
      'startBatchDownload': 'Start batch download',
      'ready': 'Ready',
      'invalidLink': 'Invalid link',
      'pasteMediaLink': 'Paste media link',
      'audioFormat': 'Audio format',
      'audioQuality': 'Audio quality',
      'systemDefault': 'System Default',
      'english': 'English',
      'arabic': 'Arabic',
      'system': 'System',
      'dark': 'Dark',
      'light': 'Light',
      'autoSaveToGallery': 'Auto-save to gallery',
      'downloadLocation': 'Download location',
      'deviceDownloadsFolder': 'Device downloads folder',
      'clearCache': 'Clear cache',
      'demoCacheOnly': 'Demo cache only',
      'privacyPolicy': 'Privacy Policy',
      'termsOfUse': 'Terms of Use',
      'contactSupport': 'Contact Support',
      'rateApp': 'Rate App',
      'placeholder': 'Placeholder',
      'comingSoon': 'Coming soon',
      'choosePlatform': 'Choose Platform',
      'instagramReel': 'Instagram Reel',
      'youtubeShort': 'YouTube Short',
      'tiktokVideo': 'TikTok Video',
      'snapchatSpotlight': 'Snapchat Spotlight',
      'readyForPlatform': 'Ready for {platform}',
      'safeZone': 'Safe Zone',
      'safeZoneHelp':
          'Keep faces, text, and important content inside this area.',
      'smartCropHelp':
          'Fills the full vertical screen by cropping the outer edges.',
      'blurredBackgroundHelp':
          'Shows the complete video with a background filling the empty space.',
      'platformPresetHelp':
          'Choose a platform preset and ApexLoad will prepare a vertical MP4.',
      'createInstagramReel': 'Create Instagram Reel',
      'createYouTubeShort': 'Create YouTube Short',
      'createTikTokVideo': 'Create TikTok Video',
      'createSnapchatSpotlight': 'Create Snapchat Spotlight',
      'videoStep': 'Video',
      'videoAudioSwapHelp':
          'This is the video whose audio will be replaced or mixed.',
      'selectAudioRange': 'Select audio range',
      'audioStart': 'Audio start',
      'audioEnd': 'Audio end',
      'selectedAudioDuration': 'Selected audio duration',
      'automaticMatch': 'Automatic Match',
      'customAudioRange': 'Custom Audio Range',
      'audioRangeHelp':
          'Choose the part of the audio you want to use. The selected audio will begin when the video starts.',
      'loopAudioUntilVideoEnds': 'Loop audio until video ends',
      'leaveRemainingVideoSilent': 'Leave remaining video silent',
      'keepOriginalAfterAudioEnds':
          'Keep original audio after selected audio ends',
      'playSelectedSegment': 'Play selected audio segment',
      'resetSelection': 'Reset selection',
      'outputSummary': 'Output summary',
      'statusSaver': 'Status Saver',
      'whatsappStatusSaver': 'WhatsApp Status Saver',
      'whatsappStatusHomeCopy':
          'Save viewed WhatsApp status photos and videos locally.',
      'whatsappStatusPremiumTitle':
          'WhatsApp Status Saver is a Premium feature.',
      'whatsappStatusPremiumMessage':
          'Preview local statuses, then upgrade to save them into ApexLoad.',
      'whatsappStatusLocalOnly':
          'WhatsApp only stores statuses on your device after you view them.',
      'whatsappStatusStep1':
          'Open WhatsApp and view the statuses you want to save.',
      'whatsappStatusStep2': 'Return to ApexLoad.',
      'whatsappStatusStep3': 'Tap Connect WhatsApp Status Folder.',
      'whatsappStatusStep4': 'Choose the WhatsApp .Statuses folder.',
      'connectWhatsappFolder': 'Connect WhatsApp Folder',
      'connectWhatsappBusinessFolder': 'Connect WhatsApp Business Folder',
      'howToFindFolder': 'How to find the folder',
      'howToFindWhatsappFolder': 'How to find the WhatsApp status folder',
      'whatsappFolderGuide':
          'In the Android folder picker, open WhatsApp or WhatsApp Business, then Media, then choose .Statuses. ApexLoad only reads files already on your phone.',
      'whatsappHowToUseCta': 'Please click here: How to use',
      'whatsappHowToUseSubtitle': 'Learn how to connect the .Statuses folder',
      'whatsappTutorialTitle': 'How to use WhatsApp Status Saver',
      'whatsappTutorialHiddenFilesNote':
          'If .Statuses does not appear, enable Show hidden files from the three-dot menu.',
      'tapImageToEnlarge': 'Tap image to enlarge',
      'whatsappTutorialStep1Title': 'Step 1 — Tap Change folder',
      'whatsappTutorialStep1Description':
          'Tap Change folder to choose the WhatsApp Status folder.',
      'whatsappTutorialStep2Title': 'Step 2 — Show hidden files',
      'whatsappTutorialStep2Description':
          'Tap the three-dot menu, then enable Show hidden files.',
      'whatsappTutorialStep3Title': 'Step 3 — Open .Statuses',
      'whatsappTutorialStep3Description':
          'Tap the .Statuses folder after hidden files are visible.',
      'whatsappTutorialStep4Title': 'Step 4 — Use this folder',
      'whatsappTutorialStep4Description':
          'Tap Use this folder after entering .Statuses.',
      'whatsappTutorialStep5Title': 'Step 5 — Allow access',
      'whatsappTutorialStep5Description':
          'Tap Allow to give ApexLoad access to the .Statuses folder.',
      'whatsappTutorialStep6Title': 'Step 6 — View your statuses',
      'whatsappTutorialStep6Description':
          'Return to ApexLoad and scroll down to view and save your WhatsApp statuses.',
      'pasteLinkTutorialTitle': 'How to copy and paste a video link',
      'pasteLinkInstagramShareTitle': 'Instagram — Tap Share',
      'pasteLinkInstagramCopyTitle': 'Instagram — Copy link',
      'pasteLinkTikTokShareTitle': 'TikTok — Tap Share',
      'pasteLinkTikTokCopyTitle': 'TikTok — Copy link',
      'pasteLinkInstagramShareDescription':
          'Open the Instagram Reel and tap the Share icon.',
      'pasteLinkCopyDescription':
          'Tap Copy link, then return to ApexLoad and paste it.',
      'pasteLinkTikTokShareDescription':
          'Open the TikTok video and tap the Share icon.',
      'pasteLinkTutorialNote':
          'After copying the link, return to ApexLoad and tap Analyze link.',
      'showHiddenFiles': 'Show hidden files',
      'whatsappInstructionsStandardTitle': 'Normal WhatsApp',
      'whatsappInstructionStandardStep1':
          'Open WhatsApp and view the statuses you want to save.',
      'whatsappInstructionStandardStep2': 'Return to ApexLoad.',
      'whatsappInstructionStandardStep3': 'Tap Connect WhatsApp Statuses.',
      'whatsappInstructionStandardStep4':
          'In the Android folder picker, open Android > media > com.whatsapp > WhatsApp > Media.',
      'whatsappInstructionStandardStep5':
          'Tap the 3-dot menu in the top corner.',
      'whatsappInstructionStandardStep6': 'Enable Show hidden files.',
      'whatsappInstructionStandardStep7': 'Open the hidden folder: .Statuses.',
      'whatsappInstructionStandardStep8': 'Tap Use this folder or Allow.',
      'whatsappInstructionsBusinessTitle': 'WhatsApp Business',
      'whatsappInstructionBusinessStep1':
          'Open WhatsApp Business and view the statuses you want to save.',
      'whatsappInstructionBusinessStep2': 'Return to ApexLoad.',
      'whatsappInstructionBusinessStep3':
          'Tap Connect WhatsApp Business Folder.',
      'whatsappInstructionBusinessStep4':
          'In the Android folder picker, open Android > media > com.whatsapp.w4b > WhatsApp Business > Media.',
      'whatsappInstructionBusinessStep5':
          'Tap the 3-dot menu in the top corner.',
      'whatsappInstructionBusinessStep6': 'Enable Show hidden files.',
      'whatsappInstructionBusinessStep7': 'Open the hidden folder: .Statuses.',
      'whatsappInstructionBusinessStep8': 'Tap Use this folder or Allow.',
      'whatsappHiddenFolderNote':
          '.Statuses is hidden by Android. If you cannot see it, tap the 3-dot menu and enable Show hidden files.',
      'whatsappStatusReadNote':
          'ApexLoad only reads statuses already saved on your device after you view them in WhatsApp.',
      'whatsappPickerHint':
          'Choose Android > media > com.whatsapp > WhatsApp > Media > .Statuses',
      'whatsappBusinessPickerHint':
          'Choose Android > media > com.whatsapp.w4b > WhatsApp Business > Media > .Statuses',
      'folderConnectionCancelled': 'Folder connection was cancelled.',
      'tryAgain': 'Try again',
      'disconnectFolder': 'Disconnect folder',
      'connected': 'Connected',
      'notConnected': 'Not connected',
      'whatsappConnected': 'WhatsApp status folder connected',
      'whatsappBusinessConnected': 'WhatsApp Business status folder connected',
      'folderSettings': 'Folder settings',
      'refresh': 'Refresh',
      'saved': 'Saved',
      'videos': 'Videos',
      'saveSelected': 'Save selected',
      'selectAll': 'Select all',
      'statusGallery': 'Status Gallery',
      'connectWhatsappFolderFirst':
          'Connect your WhatsApp .Statuses folder to show local statuses.',
      'noWhatsappStatusesFound':
          'No statuses were found. Open WhatsApp, view some statuses, then refresh.',
      'whatsappFolderAccessError':
          'Could not access the selected WhatsApp folder. Please connect it again.',
      'statusAlreadySaved': 'This status is already saved.',
      'statusSavedSuccess': 'Status saved to ApexLoad.',
      'whatsappAutoDetected': 'WhatsApp statuses detected automatically.',
      'guidedPermissionText':
          'Use the How to use guide above, then connect the .Statuses folder. You only need to do this once.',
      'connectWhatsappStatuses': 'Connect WhatsApp Statuses',
      'connectWhatsappSetupExplanation':
          'Android requires one-time permission to access viewed WhatsApp statuses. Complete these steps once, and ApexLoad will load statuses automatically afterward.',
      'whatsappSetupStep1':
          'Tap Change Folder to open the Android folder picker.',
      'whatsappSetupStep2':
          'In the folder picker, tap the three-dot menu and choose Show hidden files.',
      'whatsappSetupStep3': 'Open the .Statuses folder.',
      'whatsappSetupStep4': 'Tap Use this folder, then tap Allow.',
      'whatsappSetupStep5':
          'After that, ApexLoad will load statuses automatically.',
      'watchInstructions': 'View Instructions',
      'changeFolder': 'Change folder',
      'wrongWhatsappFolder':
          'This does not appear to be the WhatsApp .Statuses folder. Please enable hidden files and choose .Statuses.',
      'wrongWhatsappFolderSelected':
          'This is not the .Statuses folder. Please tap Change Folder, show hidden files, then choose .Statuses.',
      'setupRequired': 'Setup required',
      'validatingFolder': 'Folder selected, validating',
      'wrongFolderSelected': 'Wrong folder selected',
      'connectedNoStatuses': 'Connected, but no statuses viewed yet',
      'checkingSavedAccess': 'Checking saved access',
      'connecting': 'Connecting',
      'scanningStatuses': 'Scanning statuses',
      'foundStatuses': 'Found {count} statuses',
      'chooseFolderManually': 'Choose folder manually',
      'detectingWhatsapp': 'Detecting WhatsApp…',
      'connectedAutomatically': 'Connected automatically',
      'permissionRequired': 'Permission required',
      'permissionRevoked': 'Permission revoked',
      'folderNotFound': 'Folder not found',
      'noStatusesFound': 'No statuses found',
      'madeBy': 'Made by',
    },
    'ar': {
      'home': 'الرئيسية',
      'downloads': 'التحميلات',
      'batch': 'الدفعات',
      'settings': 'الإعدادات',
      'skip': 'تخطي',
      'continue': 'متابعة',
      'next': 'التالي',
      'back': 'رجوع',
      'close': 'إغلاق',
      'getStarted': 'ابدأ الآن',
      'onboardingTitle1': 'الصق أي رابط وسائط مدعوم',
      'onboardingDesc1': 'انسخ رابط فيديو عام من منصتك المفضلة والصقه هنا.',
      'onboardingTitle2': 'اختر الصيغة المناسبة',
      'onboardingDesc2':
          'نزّل الفيديو، استخرج الصوت، احفظ الصورة المصغّرة، والمزيد.',
      'onboardingTitle3': 'فعّل بريميوم لقوة أكبر',
      'onboardingDesc3':
          'افتح جودة FHD و 4K عند توفرها، وبدون علامة مائية عند توفرها، والدفعات، والمحرر السريع، وتبديل الصوت، والطابور الأسرع، وتجربة بدون إعلانات.',
      'pasteYourVideoLink': 'الصق رابط الفيديو',
      'analyzeLink': 'تحليل الرابط',
      'downloadCompleted': 'اكتمل التحميل',
      'downloadSavedToLibrary': 'تم حفظ التحميل في مكتبتك.',
      'analyzeFailed': 'تعذر تحليل الرابط، حاول مرة أخرى',
      'backendUnavailableDemo':
          'الخادم غير متاح حالياً، سيتم عرض نتيجة تجريبية',
      'downloadJobCreated': 'تم إنشاء مهمة التحميل',
      'downloadJobFailed': 'تعذر إنشاء مهمة التحميل، حاول مرة أخرى',
      'downloadFailed': 'فشل التحميل. جرّب صيغة أو رابطًا آخر.',
      'downloadFailedNoFiles': 'اكتمل التحميل، لكن لم يتم إرجاع أي ملفات.',
      'noMediaToShow': 'لا توجد وسائط للعرض',
      'analyzeFirstForOptions':
          'الصق رابطًا وحلّله أولًا لاختيار خيارات التحميل.',
      'noDownloadInProgress': 'لا يوجد تحميل قيد التقدم',
      'startDownloadFirst': 'ابدأ التحميل من شاشة الخيارات أولًا.',
      'noVideoSelected': 'لم يتم اختيار فيديو',
      'openQuickEditorFirst': 'افتح المحرر السريع من فيديو تم تحميله أولًا.',
      'instagramBlocked':
          'حظر Instagram هذا الطلب. حدّث ملفات تعريف الارتباط وجرب مرة أخرى.',
      'facebookPhotoUnavailable':
          'منشورات صور فيسبوك غير متاحة لهذا الرابط. جرّب رابط فيديو.',
      'youtubeRequiresAuth':
          'يتطلب يوتيوب التحقق من تسجيل الدخول. يرجى تحديث ملفات تعريف ارتباط يوتيوب من لوحة الإدارة.',
      'youtubeFormatUnavailable':
          'صيغة يوتيوب هذه غير متاحة. جرّب جودة أو رابطًا آخر.',
      'youtubeFormatsTemporarilyUnavailable':
          'صيغ فيديو يوتيوب غير متاحة مؤقتًا. يرجى تجربة رابط آخر.',
      'connectionProblem': 'مشكلة في الاتصال. حاول مرة أخرى.',
      'serverConnectionProblem':
          'تعذّر الاتصال بالخادم. يرجى التحقق من اتصال الإنترنت والمحاولة مرة أخرى.',
      'queued': 'في الانتظار',
      'downloading': 'جاري التنزيل',
      'readyToOpen': 'جاهز للفتح',
      'preparingYourFile': 'جارٍ تجهيز الملف',
      'preparingYourFileDescription':
          'جارٍ حفظ وتجهيز الملف على جهازك قبل إتاحة الإجراءات.',
      'savingToDevice': 'جارٍ الحفظ على جهازك',
      'savingFileToDevice': 'جارٍ حفظ الملف على جهازك...',
      'downloadSaveFailed':
          'اكتمل التحميل، ولكن تعذّر حفظ الملف على جهازك. يرجى المحاولة مرة أخرى.',
      'addingToGallery': 'جارٍ الإضافة إلى المعرض',
      'galleryPublishFailed':
          'تم حفظ الملف داخل ApexLoad، ولكن تعذّرت إضافته إلى المعرض.',
      'calculating': 'جارٍ الحساب...',
      'selectDownloadOption': 'اختر خيار تنزيل واحداً على الأقل',
      'upgradeToPremium': 'الترقية إلى بريميوم',
      'premium': 'بريميوم',
      'premiumRequired': 'بريميوم مطلوب',
      'legalShort': 'حمّل فقط المحتوى الذي تملكه أو لديك إذن باستخدامه.',
      'legalFull':
          'هذا التطبيق مخصص فقط لتحميل المحتوى الذي تملكه، أو لديك إذن لاستخدامه، أو المحتوى المسموح بتحميله بشكل عام. أنت مسؤول عن احترام حقوق النشر وشروط المنصات.',
      'supportedPlatforms': 'المنصات المدعومة',
      'recentDownloads': 'آخر التحميلات',
      'viewAll': 'عرض الكل',
      'pasteFirst': 'الصق رابط وسائط عام أولاً.',
      'clipboardEmpty': 'الحافظة فارغة الآن.',
      'premiumActive': 'الاشتراك المميز نشط',
      'active': 'مفعّل',
      'freePlan': 'الخطة المجانية',
      'noWatermarkDownloads': 'تحميلات بدون علامة مائية',
      'noWatermarkWhenAvailable': 'بدون علامة مائية عند توفرها',
      'homeUpgradeCopy':
          'احصل على بريميوم لتحميل بجودة FHD و 4K عند توفرها، وبدون إعلانات، والدفعات، والمحرر السريع، وتبديل الصوت، و',
      'fhd4kDownloads': 'تحميل بجودة FHD و 4K عند توفرها',
      'fhd4kDownloadsWhenAvailable': 'حمّل بجودة FHD و 4K عند توفرها.',
      'fhd4kExport': 'تصدير بجودة FHD و 4K',
      'fhd4kShort': 'FHD و 4K',
      'unlockFhd4kQuality': 'افتح جودة FHD و 4K عند توفرها',
      'monthly': 'شهري',
      'yearly': 'سنوي',
      'lifetime': 'مدى الحياة',
      'monthlyPrice': '0.99 دولار / شهرياً',
      'yearlyPrice': '9.99 دولار / سنوياً',
      'lifetimePrice': '24.99 دولار مرة واحدة',
      'import': 'استيراد',
      'validate': 'تحقق',
      'language': 'اللغة',
      'theme': 'المظهر',
      'quickEditor': 'المحرر السريع',
      'quickEditorSubtitle':
          'قص الفيديو، كتم الصوت، استخراج الصوت، وضغط الفيديو.',
      'quickEditorPremiumTitle': 'المحرر السريع ميزة بريميوم',
      'quickEditorPremiumMessage':
          'قم بالترقية لقص الفيديو، كتم الصوت، استخراج الصوت، استبدال الصوت، وضغط الفيديو',
      'editVideo': 'تعديل الفيديو',
      'trimVideo': 'قص الفيديو',
      'muteVideo': 'كتم الصوت',
      'extractAudio': 'استخراج الصوت',
      'compressVideo': 'ضغط الفيديو',
      'exportEditedVideo': 'تصدير الفيديو المعدل',
      'format': 'الصيغة',
      'startTime': 'وقت البداية',
      'endTime': 'وقت النهاية',
      'trimDuration': 'مدة القص',
      'seconds': 'ثواني',
      'previewSelection': 'معاينة المقطع',
      'validTrimRange': 'يرجى اختيار نطاق قص صحيح.',
      'videoPreviewUnavailable': 'معاينة الفيديو غير متاحة لهذا الملف.',
      'applyTrim': 'تطبيق القص',
      'removeOriginalAudio': 'إزالة الصوت الأصلي',
      'applyMute': 'تطبيق الكتم',
      'standard': 'عادي',
      'high': 'عالي',
      'smallFile': 'ملف صغير',
      'balanced': 'متوازن',
      'highQuality': 'جودة عالية',
      'highestQuality': 'أعلى جودة',
      'estimatedReduction': 'تقليل الحجم المتوقع: أصغر بنسبة 35%',
      'compress': 'ضغط',
      'exportSettings': 'إعدادات التصدير',
      'saveToGallery': 'حفظ في المعرض',
      'noWatermarkNote': 'تطبق فقط عندما توفرها المنصة أو المصدر.',
      'processingLocally': 'تتم المعالجة محلياً على هذا الجهاز',
      'processingEditor': 'تتم المعالجة محليًا على هذا الجهاز',
      'trimSuccess': 'تم تطبيق القص بنجاح',
      'muteSuccess': 'تم كتم الفيديو بنجاح',
      'audioExtractedSuccess': 'تم استخراج الصوت بنجاح',
      'compressSuccess': 'تم ضغط الفيديو بنجاح',
      'exportSuccess': 'تم تصدير الفيديو المعدل بنجاح',
      'couldNotEditFile': 'تعذّر تعديل هذا الملف. يرجى تجربة ملف أو خيار آخر.',
      'originalFileMissing':
          'تعذّر العثور على الملف الأصلي. يرجى تنزيله مرة أخرى ثم محاولة تعديله.',
      'fileMustBeSavedBeforeEdit':
          'يجب حفظ هذا الملف على جهازك قبل تعديله. يرجى تنزيله مرة أخرى.',
      'savedToApexLoad': 'تم الحفظ في ApexLoad',
      'editedFileSavedSuccess': 'تم حفظ الملف المعدّل بنجاح.',
      'couldNotGenerateThumbnail': 'تعذّر إنشاء الصورة المصغّرة.',
      'deleteThisFile': 'هل تريد حذف هذا الملف؟',
      'fileDeleted': 'تم حذف الملف.',
      'sharingFailed': 'تعذّرت المشاركة. يرجى المحاولة مرة أخرى.',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'older': 'أقدم',
      'edited': 'معدّل',
      'editor': 'المحرر',
      'editorToolSoon': 'سيتم إضافة هذه الأداة قريبًا.',
      'quickEditorBenefit':
          'قص الفيديو، كتم الصوت، استخراج الصوت، وضغط الفيديو.',
      'platformTikTok': 'تيك توك',
      'platformInstagram': 'إنستغرام',
      'platformFacebook': 'فيسبوك',
      'platformXTwitter': 'إكس/تويتر',
      'platformYouTubeShorts': 'يوتيوب شورتس',
      'platformPinterest': 'بنترست',
      'platformReddit': 'ريديت',
      'platformSnapchat': 'سناب شات',
      'unlockPremiumTitle': 'افتح ApexLoad بريميوم',
      'premiumSubtitle': 'سرعة أكثر. جودة أعلى. بدون حدود.',
      'premiumDownloads': 'تحميلات بريميوم',
      'premiumCreatorTools': 'أدوات صناع المحتوى',
      'premiumEditorTools': 'أدوات التعديل المميزة',
      'premiumUnlimitedDescription': 'حمّل بدون حدود يومية.',
      'premiumHdDownloads': 'تحميل بجودة عالية حتى 4K',
      'premiumHdDownloadsDescription': 'جودة أعلى عند توفرها من المصدر.',
      'premiumBatchDescription': 'حمّل حتى 5 روابط في كل مرة.',
      'premiumMp3Extraction': 'استخراج الصوت MP3',
      'premiumMp3Description': 'احفظ الصوت من الفيديوهات المدعومة.',
      'premiumNoWatermark': 'بدون علامة مائية عند الإمكان',
      'premiumNoWatermarkDescription': 'تُطبق تلقائياً عندما يدعم المصدر ذلك.',
      'premiumQuickEditorTools': 'أدوات التعديل السريع',
      'premiumFasterQueue': 'أولوية في المعالجة',
      'premiumFasterQueueDescription': 'أولوية للمهام المدعومة.',
      'premiumNoAdsDescription': 'استخدم ApexLoad بدون مقاطعة إعلانية.',
      'noAds': 'بدون إعلانات',
      'batchDownloads': 'تحميل الدفعات',
      'audioExtraction': 'استخراج الصوت',
      'fasterQueue': 'طابور أسرع',
      'unlimitedDownloads': 'تحميلات غير محدودة',
      'cloudSave': 'حفظ سحابي',
      'bestValue': 'أفضل قيمة',
      'premiumActivatedDemo': 'تم تفعيل بريميوم في النسخة التجريبية.',
      'premiumActiveButton': 'الاشتراك المميز نشط',
      'termsPrivacyPlaceholder':
          'الشروط والخصوصية عناصر مؤقتة في نسخة الواجهة الحالية.',
      'downloadOptions': 'خيارات التحميل',
      'chooseFormat': 'اختر الصيغة',
      'customFilename': 'اسم الملف المخصص',
      'download': 'تحميل',
      'howToUse': 'طريقة الاستخدام',
      'openAudioTool': 'فتح أداة استخراج الصوت',
      'viewPremium': 'عرض بريميوم',
      'premiumOption': 'خيار بريميوم',
      'premiumFeatureSummary':
          'افتح جودة FHD و 4K عند توفرها، وبدون علامة مائية عند توفرها، والمحرر السريع، واستخراج الصوت، وتحميل الدفعات.',
      'downloadProgress': 'تقدم التحميل',
      'openLibrary': 'فتح المكتبة',
      'downloadAnother': 'تحميل رابط آخر',
      'cancel': 'إلغاء',
      'platform': 'المنصة',
      'speed': 'السرعة',
      'queuePosition': 'ترتيب الطابور',
      'savedLocally': 'تم الحفظ محلياً',
      'done': 'تم',
      'searchDownloads': 'البحث في التحميلات',
      'noDownloadsYet': 'لا توجد تحميلات بعد',
      'pasteLinkOnHome': 'الصق رابطاً في الشاشة الرئيسية للبدء.',
      'renameFile': 'إعادة تسمية الملف',
      'filename': 'اسم الملف',
      'save': 'حفظ',
      'upgradeNow': 'الترقية الآن',
      'maybeLater': 'ربما لاحقاً',
      'dailyLimitReachedTitle': 'تم الوصول إلى الحد اليومي',
      'dailyLimitReachedMessage':
          'لقد وصلت إلى الحد اليومي المجاني. قم بالترقية إلى بريميوم لتحميلات غير محدودة.',
      'freeDownloadsLeft': 'التحميلات المجانية المتبقية اليوم: {count}/5',
      'adPlaceholderTitle': 'إعلان تجريبي',
      'adPlaceholderMessage': 'هنا سيظهر الإعلان للمستخدمين المجانيين',
      'premiumActivatedSuccess': 'تم تفعيل بريميوم بنجاح.',
      'premiumMonthly': 'بريميوم شهري',
      'premiumYearly': 'بريميوم سنوي',
      'premiumLifetime': 'بريميوم مدى الحياة',
      'fhd4kPremiumTitle': 'تحميلات FHD و 4K ميزة بريميوم.',
      'fhd4kPremiumMessage': 'قم بالترقية للتحميل بجودة أعلى عند توفرها.',
      'batchPremiumTitle': 'تحميل الدفعات ميزة بريميوم.',
      'batchPremiumMessage': 'قم بالترقية لتحميل عدة روابط معاً.',
      'audioExtractionPremiumTitle': 'استخراج الصوت ميزة بريميوم.',
      'audioExtractionPremiumMessage':
          'قم بالترقية لاستخراج الصوت من روابط الوسائط.',
      'noWatermarkPremiumTitle': 'التحميل بدون علامة مائية ميزة بريميوم.',
      'noWatermarkPremiumMessage':
          'متاح عندما توفر المنصة نسخة بدون علامة مائية.',
      'audioSwapPremiumTitle': 'تبديل الصوت ميزة بريميوم.',
      'audioSwapPremiumMessage':
          'قم بالترقية لاستبدال صوت الفيديو الأصلي بصوت من جهازك.',
      'audioSwap': 'تبديل الصوت',
      'audioSwapReplaceAudio': 'تبديل الصوت / استبدال الصوت',
      'replaceAudio': 'استبدال الصوت',
      'audioSwapSubtitle': 'استبدل صوت الفيديو الأصلي بصوت من جهازك',
      'audioSwapDescription': 'استبدل صوت الفيديو الأصلي بملف صوتي من هاتفك.',
      'chooseAudioFile': 'اختر ملفًا صوتيًا',
      'pickAudioFile': 'اختيار ملف صوتي',
      'selectedAudio': 'الصوت المختار',
      'audioFormatSupport': 'سيتم دعم MP3 / M4A / WAV لاحقاً',
      'audioStartPosition': 'بداية الصوت داخل الفيديو',
      'removeOriginalSound': 'إزالة الصوت الأصلي',
      'keepOriginalSoundSoftly': 'إبقاء الصوت الأصلي منخفض',
      'audioVolume': 'مستوى الصوت',
      'preview': 'معاينة',
      'applyAudioSwap': 'تطبيق تبديل الصوت',
      'audioReplacedSuccess': 'تم استبدال الصوت بنجاح.',
      'couldNotReplaceAudio': 'تعذّر استبدال الصوت. يرجى تجربة ملف صوتي آخر.',
      'noAudioSelected': 'اختر ملفاً صوتياً أولاً.',
      'originalAudio': 'الصوت الأصلي',
      'replaceOriginalAudio': 'استبدال الصوت الأصلي',
      'removeOriginalAudioOnly': 'إزالة الصوت الأصلي فقط',
      'chooseNewAudio': 'اختيار صوت جديد',
      'noNewAudioNeeded': 'لا تحتاج إلى ملف صوتي جديد عند إزالة الصوت فقط.',
      'previewAndApply': 'المعاينة والتطبيق',
      'previewWithNewAudio': 'معاينة بالصوت الجديد',
      'audioTrimmedToVideoLength':
          'سيتم ضبط الصوت الجديد ليتناسب مع مدة الفيديو.',
      'audioShorterThanVideo':
          'إذا كان الصوت أقصر، سينتهي التصدير عند نهاية الصوت الجديد.',
      'advancedOptions': 'خيارات متقدمة',
      'videoToGif': 'تحويل الفيديو إلى GIF',
      'createGif': 'إنشاء GIF',
      'previewGifRange': 'معاينة جزء GIF',
      'gifCreatedSuccess': 'تم إنشاء GIF بنجاح.',
      'couldNotCreateGif': 'تعذّر إنشاء GIF. جرّب مدة أقصر.',
      'videoToGifPremiumTitle': 'تحويل الفيديو إلى GIF ميزة بريميوم.',
      'reelsShortsCreator': 'صانع Reels/Shorts',
      'createReelShort': 'إنشاء Reel/Short',
      'chooseOutputFormat': 'اختر تنسيق الإخراج',
      'resizeMode': 'طريقة تغيير المقاس',
      'smartCrop': 'قص ذكي',
      'fitWithBlurredBackground': 'ملاءمة مع خلفية',
      'fitWithSolidBackground': 'ملاءمة مع خلفية ثابتة',
      'centerCrop': 'قص من الوسط',
      'reelShortCreatedSuccess': 'تم إنشاء Reel/Short بنجاح.',
      'couldNotCreateReelShort': 'تعذّر إنشاء Reel/Short. يرجى تجربة خيار آخر.',
      'reelsShortsPremiumTitle': 'صانع Reels/Shorts ميزة بريميوم.',
      'chooseVideo': 'اختيار فيديو',
      'selectedVideo': 'الفيديو المختار',
      'gifSettings': 'إعدادات GIF',
      'quality': 'الجودة',
      'size': 'الحجم',
      'small': 'صغير',
      'medium': 'متوسط',
      'original': 'الأصلي',
      'fps': 'إطار/ثانية',
      'loop': 'تكرار',
      'reelsShortsOutputNote':
          'يتم التصدير محليًا بصيغة MP4 مناسبة للمنصات الاجتماعية.',
      'demoPreviewReady': 'المعاينة التجريبية جاهزة.',
      'somethingWentWrong': 'حدث خطأ، حاول مرة أخرى',
      'demoActionForNow': '{action} حالياً مجرد تجربة',
      'sharingSoon': 'ستتم إضافة المشاركة قريبًا.',
      'couldNotOpenFile': 'تعذّر فتح هذا الملف. يرجى المحاولة مرة أخرى.',
      'fileNoLongerAvailable': 'هذا الملف لم يعد متاحًا على جهازك.',
      'demoExtractionPrepared': 'تم تجهيز استخراج {format} كتجربة.',
      'batchQueueCreated':
          'تم إنشاء قائمة تجريبية. سيتم تشغيلها من الخادم لاحقاً.',
      'batchLimitExceeded': 'يمكنك تحميل ما يصل إلى 5 روابط في كل مرة.',
      'notAvailableOnClip': 'غير متوفر لهذا المقطع',
      'notAvailableForImage': 'غير متوفر لهذه الصورة',
      'Instagram photo posts are not available for this link. Try a Reel/video link.':
          'منشورات الصور في إنستغرام غير متاحة لهذا الرابط. جرّب رابط Reel أو فيديو.',
      'Facebook photo posts are not available for this link. Try a video link.':
          'منشورات صور فيسبوك غير متاحة لهذا الرابط. جرّب رابط فيديو.',
      'noWatermarkApplied': 'سيتم التحميل بدون علامة مائية عند توفر ذلك',
      'downloadSelected': 'تحميل المحدد',
      'downloadSelectedItems': 'تحميل العناصر المحددة',
      'downloadSelectedItemsCount': 'تحميل {count} عناصر محددة',
      'selectedItemsDownloaded': 'تم تحميل العناصر المحددة بنجاح',
      'chooseImageFormat': 'اختر صيغة الصورة',
      'originalImage': 'الصورة الأصلية',
      'highQualityImage': 'صورة عالية الجودة',
      'compressedImage': 'صورة مضغوطة',
      'jpgImage': 'صورة JPG',
      'pngImage': 'صورة PNG',
      'bestAvailableQuality': 'أفضل جودة متاحة',
      'premiumQualityWhenAvailable': 'جودة بريميوم عند توفرها',
      'smallerFileSize': 'حجم ملف أصغر',
      'standardFormat': 'صيغة قياسية',
      'whenAvailable': 'عند توفرها',
      'imagePremiumTitle': 'الصور عالية الجودة ميزة بريميوم.',
      'imagePremiumMessage': 'قم بالترقية لتحميل صيغ الصور المميزة عند توفرها.',
      'yourApexLoad': 'حساب ApexLoad الخاص بك',
      'appStatus': 'حالة التطبيق',
      'plan': 'الخطة',
      'downloadsToday': 'تحميلات اليوم',
      'storageUsed': 'المساحة المستخدمة',
      'locked': 'مقفل',
      'unlocked': 'مفتوح',
      'free': 'مجاني',
      'all': 'الكل',
      'video': 'فيديو',
      'audio': 'صوت',
      'images': 'صور',
      'open': 'فتح',
      'share': 'مشاركة',
      'edit': 'تعديل',
      'rename': 'إعادة تسمية',
      'delete': 'حذف',
      'goHome': 'العودة للرئيسية',
      'pasteOneLinkPerLine': 'الصق رابطاً عاماً في كل سطر',
      'queuePreview': 'معاينة القائمة',
      'startBatchDownload': 'بدء تحميل الدفعة',
      'ready': 'جاهز',
      'invalidLink': 'رابط غير صالح',
      'pasteMediaLink': 'الصق رابط الوسائط',
      'audioFormat': 'صيغة الصوت',
      'audioQuality': 'جودة الصوت',
      'systemDefault': 'افتراضي النظام',
      'english': 'English',
      'arabic': 'العربية',
      'system': 'النظام',
      'dark': 'داكن',
      'light': 'فاتح',
      'autoSaveToGallery': 'الحفظ التلقائي في المعرض',
      'downloadLocation': 'مكان التحميل',
      'deviceDownloadsFolder': 'مجلد التحميلات على الجهاز',
      'clearCache': 'مسح الذاكرة المؤقتة',
      'demoCacheOnly': 'ذاكرة تجريبية فقط',
      'privacyPolicy': 'سياسة الخصوصية',
      'termsOfUse': 'شروط الاستخدام',
      'contactSupport': 'التواصل مع الدعم',
      'rateApp': 'تقييم التطبيق',
      'placeholder': 'عنصر مؤقت',
      'comingSoon': 'قريباً',
      'choosePlatform': 'اختر المنصة',
      'instagramReel': 'Instagram Reel',
      'youtubeShort': 'YouTube Short',
      'tiktokVideo': 'TikTok Video',
      'snapchatSpotlight': 'Snapchat Spotlight',
      'readyForPlatform': 'جاهز لـ {platform}',
      'safeZone': 'منطقة آمنة',
      'safeZoneHelp': 'أبقِ الوجوه والنصوص والمحتوى المهم داخل هذه المنطقة.',
      'smartCropHelp': 'يملأ الشاشة العمودية بالكامل مع قص الحواف الخارجية.',
      'blurredBackgroundHelp':
          'يعرض الفيديو بالكامل مع خلفية تملأ المساحة الفارغة.',
      'platformPresetHelp':
          'اختر منصة وسيجهز ApexLoad فيديو MP4 عموديًا مناسبًا.',
      'createInstagramReel': 'إنشاء Instagram Reel',
      'createYouTubeShort': 'إنشاء YouTube Short',
      'createTikTokVideo': 'إنشاء TikTok Video',
      'createSnapchatSpotlight': 'إنشاء Snapchat Spotlight',
      'videoStep': 'الفيديو',
      'videoAudioSwapHelp': 'هذا هو الفيديو الذي سيتم استبدال صوته أو دمجه.',
      'selectAudioRange': 'حدد نطاق الصوت',
      'audioStart': 'بداية الصوت',
      'audioEnd': 'نهاية الصوت',
      'selectedAudioDuration': 'مدة الصوت المحددة',
      'automaticMatch': 'مطابقة تلقائية',
      'customAudioRange': 'نطاق صوت مخصص',
      'audioRangeHelp':
          'اختر الجزء الذي تريد استخدامه من الملف الصوتي. سيبدأ الصوت المحدد عند بداية الفيديو.',
      'loopAudioUntilVideoEnds': 'تكرار الصوت حتى نهاية الفيديو',
      'leaveRemainingVideoSilent': 'ترك الجزء المتبقي من الفيديو صامتًا',
      'keepOriginalAfterAudioEnds':
          'الإبقاء على الصوت الأصلي بعد انتهاء الصوت المحدد',
      'playSelectedSegment': 'تشغيل الجزء المحدد',
      'resetSelection': 'إعادة التحديد',
      'outputSummary': 'ملخص الإخراج',
      'statusSaver': 'حافظ الحالات',
      'whatsappStatusSaver': 'حفظ حالات واتساب',
      'whatsappStatusHomeCopy': 'احفظ صور وفيديوهات حالات واتساب التي شاهدتها.',
      'whatsappStatusPremiumTitle': 'حافظ حالات واتساب ميزة بريميوم.',
      'whatsappStatusPremiumMessage':
          'يمكنك معاينة الحالات المحلية، والترقية لحفظها داخل ApexLoad.',
      'whatsappStatusLocalOnly':
          'يحفظ واتساب الحالات على جهازك بعد مشاهدتها فقط.',
      'whatsappStatusStep1': 'افتح واتساب وشاهد الحالات التي تريد حفظها.',
      'whatsappStatusStep2': 'ارجع إلى ApexLoad.',
      'whatsappStatusStep3': 'اضغط ربط مجلد حالات واتساب.',
      'whatsappStatusStep4': 'اختر مجلد WhatsApp .Statuses.',
      'connectWhatsappFolder': 'ربط مجلد واتساب',
      'connectWhatsappBusinessFolder': 'ربط مجلد واتساب بزنس',
      'howToFindFolder': 'طريقة العثور على المجلد',
      'howToFindWhatsappFolder': 'طريقة العثور على مجلد حالات واتساب',
      'whatsappFolderGuide':
          'في منتقي المجلدات على أندرويد، افتح WhatsApp أو WhatsApp Business ثم Media ثم اختر .Statuses. يقرأ ApexLoad الملفات الموجودة على هاتفك فقط.',
      'whatsappHowToUseCta': 'اضغط هنا لمعرفة طريقة الاستخدام',
      'whatsappHowToUseSubtitle': 'تعرّف على طريقة ربط مجلد .Statuses',
      'whatsappTutorialTitle': 'طريقة استخدام حفظ حالات واتساب',
      'whatsappTutorialHiddenFilesNote':
          'إذا لم يظهر مجلد .Statuses، فعّل خيار إظهار الملفات المخفية من قائمة الثلاث نقاط.',
      'tapImageToEnlarge': 'اضغط على الصورة للتكبير',
      'whatsappTutorialStep1Title': 'الخطوة 1 — اضغط تغيير المجلد',
      'whatsappTutorialStep1Description':
          'اضغط تغيير المجلد لاختيار مجلد حالات واتساب.',
      'whatsappTutorialStep2Title': 'الخطوة 2 — إظهار الملفات المخفية',
      'whatsappTutorialStep2Description':
          'اضغط قائمة الثلاث نقاط، ثم فعّل إظهار الملفات المخفية.',
      'whatsappTutorialStep3Title': 'الخطوة 3 — افتح مجلد .Statuses',
      'whatsappTutorialStep3Description':
          'اضغط مجلد .Statuses بعد ظهور الملفات المخفية.',
      'whatsappTutorialStep4Title': 'الخطوة 4 — استخدم هذا المجلد',
      'whatsappTutorialStep4Description':
          'اضغط استخدام هذا المجلد بعد الدخول إلى .Statuses.',
      'whatsappTutorialStep5Title': 'الخطوة 5 — السماح بالوصول',
      'whatsappTutorialStep5Description':
          'اضغط سماح لمنح ApexLoad الوصول إلى مجلد .Statuses.',
      'whatsappTutorialStep6Title': 'الخطوة 6 — اعرض حالات واتساب',
      'whatsappTutorialStep6Description':
          'ارجع إلى ApexLoad ومرّر للأسفل لعرض حالات واتساب وحفظها.',
      'pasteLinkTutorialTitle': 'طريقة نسخ ولصق رابط الفيديو',
      'pasteLinkInstagramShareTitle': 'إنستغرام — اضغط مشاركة',
      'pasteLinkInstagramCopyTitle': 'إنستغرام — نسخ الرابط',
      'pasteLinkTikTokShareTitle': 'تيك توك — اضغط مشاركة',
      'pasteLinkTikTokCopyTitle': 'تيك توك — نسخ الرابط',
      'pasteLinkInstagramShareDescription':
          'افتح ريل إنستغرام واضغط على أيقونة المشاركة.',
      'pasteLinkCopyDescription':
          'اضغط نسخ الرابط، ثم ارجع إلى ApexLoad والصقه.',
      'pasteLinkTikTokShareDescription':
          'افتح فيديو تيك توك واضغط على أيقونة المشاركة.',
      'pasteLinkTutorialNote':
          'بعد نسخ الرابط، ارجع إلى ApexLoad واضغط تحليل الرابط.',
      'showHiddenFiles': 'إظهار الملفات المخفية',
      'whatsappInstructionsStandardTitle': 'واتساب العادي',
      'whatsappInstructionStandardStep1':
          'افتح واتساب وشاهد الحالات التي تريد حفظها.',
      'whatsappInstructionStandardStep2': 'ارجع إلى ApexLoad.',
      'whatsappInstructionStandardStep3': 'اضغط ربط حالات واتساب.',
      'whatsappInstructionStandardStep4':
          'في منتقي المجلدات على أندرويد، افتح Android > media > com.whatsapp > WhatsApp > Media.',
      'whatsappInstructionStandardStep5':
          'اضغط قائمة الثلاث نقاط في الزاوية العلوية.',
      'whatsappInstructionStandardStep6': 'فعّل إظهار الملفات المخفية.',
      'whatsappInstructionStandardStep7': 'افتح المجلد المخفي: .Statuses.',
      'whatsappInstructionStandardStep8': 'اضغط استخدام هذا المجلد أو سماح.',
      'whatsappInstructionsBusinessTitle': 'واتساب بزنس',
      'whatsappInstructionBusinessStep1':
          'افتح واتساب بزنس وشاهد الحالات التي تريد حفظها.',
      'whatsappInstructionBusinessStep2': 'ارجع إلى ApexLoad.',
      'whatsappInstructionBusinessStep3': 'اضغط ربط مجلد واتساب بزنس.',
      'whatsappInstructionBusinessStep4':
          'في منتقي المجلدات على أندرويد، افتح Android > media > com.whatsapp.w4b > WhatsApp Business > Media.',
      'whatsappInstructionBusinessStep5':
          'اضغط قائمة الثلاث نقاط في الزاوية العلوية.',
      'whatsappInstructionBusinessStep6': 'فعّل إظهار الملفات المخفية.',
      'whatsappInstructionBusinessStep7': 'افتح المجلد المخفي: .Statuses.',
      'whatsappInstructionBusinessStep8': 'اضغط استخدام هذا المجلد أو سماح.',
      'whatsappHiddenFolderNote':
          'مجلد .Statuses مخفي بواسطة أندرويد. إذا لم يظهر لك، اضغط على قائمة الثلاث نقاط وفعّل إظهار الملفات المخفية.',
      'whatsappStatusReadNote':
          'يقرأ ApexLoad الحالات المحفوظة على جهازك فقط بعد مشاهدتها في واتساب.',
      'whatsappPickerHint':
          'اختر Android > media > com.whatsapp > WhatsApp > Media > .Statuses',
      'whatsappBusinessPickerHint':
          'اختر Android > media > com.whatsapp.w4b > WhatsApp Business > Media > .Statuses',
      'folderConnectionCancelled': 'تم إلغاء ربط المجلد.',
      'tryAgain': 'حاول مرة أخرى',
      'disconnectFolder': 'فصل المجلد',
      'connected': 'متصل',
      'notConnected': 'غير متصل',
      'whatsappConnected': 'تم ربط مجلد حالات واتساب',
      'whatsappBusinessConnected': 'تم ربط مجلد حالات واتساب بزنس',
      'folderSettings': 'إعدادات المجلد',
      'refresh': 'تحديث',
      'saved': 'محفوظ',
      'videos': 'فيديوهات',
      'saveSelected': 'حفظ المحدد',
      'selectAll': 'تحديد الكل',
      'statusGallery': 'معرض الحالات',
      'connectWhatsappFolderFirst':
          'اربط مجلد .Statuses في واتساب لعرض الحالات المحلية.',
      'noWhatsappStatusesFound':
          'لم يتم العثور على حالات. افتح واتساب وشاهد بعض الحالات ثم حدّث الصفحة.',
      'whatsappFolderAccessError':
          'تعذّر الوصول إلى مجلد واتساب المحدد. يرجى ربطه مرة أخرى.',
      'statusAlreadySaved': 'تم حفظ هذه الحالة مسبقًا.',
      'statusSavedSuccess': 'تم حفظ الحالة في ApexLoad.',
      'whatsappAutoDetected': 'تم اكتشاف حالات واتساب تلقائيًا.',
      'guidedPermissionText':
          'استخدم دليل طريقة الاستخدام أعلاه، ثم اربط مجلد .Statuses. ستحتاج إلى تنفيذ هذه الخطوة مرة واحدة فقط.',
      'chooseFolderManually': 'اختيار المجلد يدويًا',
      'detectingWhatsapp': 'جارٍ اكتشاف واتساب…',
      'connectedAutomatically': 'تم الاتصال تلقائيًا',
      'permissionRequired': 'يلزم منح الإذن',
      'permissionRevoked': 'تم إلغاء الإذن',
      'folderNotFound': 'لم يتم العثور على المجلد',
      'noStatusesFound': 'لا توجد حالات',
      'madeBy': 'صنع بواسطة',
    },
  };

  String t(String key) =>
      _values[locale.languageCode]?[key] ?? _values['en']![key] ?? key;

  String platformName(String name) {
    return switch (name) {
      'TikTok' => t('platformTikTok'),
      'Instagram' => t('platformInstagram'),
      'Facebook' => t('platformFacebook'),
      'X/Twitter' => t('platformXTwitter'),
      'YouTube Shorts' => t('platformYouTubeShorts'),
      'Pinterest' => t('platformPinterest'),
      'Reddit' => t('platformReddit'),
      'Snapchat' => t('platformSnapchat'),
      _ => name,
    };
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
