import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const delegate = _AppLocalizationsDelegate();

  static const _values = <String, Map<String, String>>{
    'en': {
      'home': 'Home',
      'downloads': 'Downloads',
      'batch': 'Batch',
      'settings': 'Settings',
      'skip': 'Skip',
      'continue': 'Continue',
      'getStarted': 'Get Started',
      'onboardingTitle1': 'Paste any supported media link',
      'onboardingDesc1':
          'Copy a public video link from your favorite platform and paste it here.',
      'onboardingTitle2': 'Choose your format',
      'onboardingDesc2':
          'Download video, extract audio, save thumbnails, and more.',
      'onboardingTitle3': 'Go Premium for more power',
      'onboardingDesc3':
          'Unlock FHD & 4K quality, no watermark when available, batch downloads, Quick Editor, Audio Swap, faster queue, and no ads.',
      'pasteYourVideoLink': 'Paste your video link',
      'analyzeLink': 'Analyze link',
      'downloadCompleted': 'Download completed',
      'analyzeFailed': 'Could not analyze this link. Please try again.',
      'backendUnavailableDemo': 'Backend unavailable. Showing demo result.',
      'downloadJobCreated': 'Download job created.',
      'downloadJobFailed': 'Could not create download job. Please try again.',
      'downloadFailed': 'Download failed. Please try another format or link.',
      'downloadFailedNoFiles':
          'Download completed, but no files were returned.',
      'noMediaToShow': 'No media to show',
      'analyzeFirstForOptions':
          'Paste and analyze a link first to choose download options.',
      'noDownloadInProgress': 'No download in progress',
      'startDownloadFirst': 'Start a download from the options screen first.',
      'noVideoSelected': 'No video selected',
      'openQuickEditorFirst':
          'Open Quick Editor from a downloaded video first.',
      'instagramBlocked':
          'Instagram blocked this request. Please refresh Instagram cookies and try again.',
      'connectionProblem': 'Connection problem. Please try again.',
      'queued': 'Queued',
      'downloading': 'Downloading',
      'readyToOpen': 'Ready to open',
      'selectDownloadOption': 'Please select at least one download option.',
      'upgradeToPremium': 'Upgrade to Premium',
      'premium': 'Premium',
      'premiumRequired': 'Premium required',
      'legalShort': 'Only download content you own or have permission to use.',
      'legalFull':
          'This app is intended only for downloading content you own, have permission to use, or content that is publicly allowed to be downloaded. Users are responsible for respecting copyright and platform terms.',
      'supportedPlatforms': 'Supported platforms',
      'recentDownloads': 'Recent downloads',
      'viewAll': 'View all',
      'pasteFirst': 'Paste a public media link first.',
      'clipboardEmpty': 'Clipboard is empty right now.',
      'premiumActive': 'Premium active',
      'active': 'Active',
      'freePlan': 'Free plan',
      'noWatermarkDownloads': 'No watermark downloads',
      'noWatermarkWhenAvailable': 'No watermark when available',
      'homeUpgradeCopy':
          'Go Premium for FHD & 4K downloads, no ads, batch downloads, Quick Editor, Audio Swap, and',
      'fhd4kDownloads': 'FHD & 4K downloads when available',
      'fhd4kDownloadsWhenAvailable': 'Download in FHD & 4K when available.',
      'fhd4kExport': 'FHD & 4K export',
      'fhd4kShort': 'FHD & 4K',
      'unlockFhd4kQuality': 'Unlock FHD & 4K quality',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'lifetime': 'Lifetime',
      'monthlyPrice': r'$0.99/month',
      'yearlyPrice': r'$9.99/year',
      'lifetimePrice': r'$24.99 one-time',
      'import': 'Import',
      'validate': 'Validate',
      'language': 'Language',
      'theme': 'Theme',
      'quickEditor': 'Quick Editor',
      'quickEditorSubtitle':
          'Trim, mute, extract audio, and compress your videos.',
      'quickEditorPremiumTitle': 'Quick Editor is a Premium feature.',
      'quickEditorPremiumMessage':
          'Upgrade to trim, mute, extract audio, replace audio, and compress your videos.',
      'editVideo': 'Edit Video',
      'trimVideo': 'Trim video',
      'muteVideo': 'Mute video',
      'extractAudio': 'Extract audio',
      'compressVideo': 'Compress video',
      'exportEditedVideo': 'Export edited video',
      'format': 'Format',
      'startTime': 'Start time',
      'endTime': 'End time',
      'trimDuration': 'Trim duration',
      'seconds': 'seconds',
      'applyTrim': 'Apply Trim',
      'removeOriginalAudio': 'Remove original audio',
      'applyMute': 'Apply Mute',
      'standard': 'Standard',
      'high': 'High',
      'smallFile': 'Small file',
      'balanced': 'Balanced',
      'highQuality': 'High quality',
      'highestQuality': 'Highest quality',
      'estimatedReduction': 'Estimated size reduction: 35% smaller',
      'compress': 'Compress',
      'exportSettings': 'Export Settings',
      'saveToGallery': 'Save to gallery',
      'noWatermarkNote': 'Applied only when the platform/source provides it.',
      'processingLocally': 'Processing locally on this device',
      'trimSuccess': 'Trim applied successfully',
      'muteSuccess': 'Video muted successfully',
      'audioExtractedSuccess': 'Audio extracted successfully',
      'compressSuccess': 'Video compressed successfully',
      'exportSuccess': 'Edited video exported successfully',
      'quickEditorBenefit': 'Trim, mute, extract audio, and compress videos.',
      'platformTikTok': 'TikTok',
      'platformInstagram': 'Instagram',
      'platformFacebook': 'Facebook',
      'platformXTwitter': 'X/Twitter',
      'platformYouTubeShorts': 'YouTube Shorts',
      'platformPinterest': 'Pinterest',
      'platformReddit': 'Reddit',
      'platformSnapchat': 'Snapchat',
      'unlockPremiumTitle': 'Unlock ApexLoad Premium',
      'premiumSubtitle': 'More speed. More quality. No limits.',
      'noAds': 'No ads',
      'batchDownloads': 'Batch downloads',
      'audioExtraction': 'Audio extraction',
      'fasterQueue': 'Faster queue',
      'unlimitedDownloads': 'Unlimited downloads',
      'cloudSave': 'Cloud save',
      'bestValue': 'Best Value',
      'premiumActivatedDemo': 'Premium activated for this demo.',
      'premiumActiveButton': 'Premium Active',
      'termsPrivacyPlaceholder':
          'Terms and Privacy are placeholders for this frontend version.',
      'downloadOptions': 'Download options',
      'chooseFormat': 'Choose format',
      'customFilename': 'Custom filename',
      'download': 'Download',
      'openAudioTool': 'Open audio extraction tool',
      'viewPremium': 'View Premium',
      'premiumOption': 'Premium option',
      'premiumFeatureSummary':
          'Unlock FHD & 4K quality, no watermark when available, Quick Editor, audio extraction, and batch downloads.',
      'downloadProgress': 'Download progress',
      'openLibrary': 'Open Library',
      'downloadAnother': 'Download Another',
      'cancel': 'Cancel',
      'platform': 'Platform',
      'speed': 'Speed',
      'queuePosition': 'Queue position',
      'savedLocally': 'Saved locally',
      'done': 'Done',
      'searchDownloads': 'Search downloads',
      'noDownloadsYet': 'No downloads yet',
      'pasteLinkOnHome': 'Paste a link on the Home screen to start.',
      'renameFile': 'Rename file',
      'filename': 'Filename',
      'save': 'Save',
      'upgradeNow': 'Upgrade Now',
      'maybeLater': 'Maybe Later',
      'dailyLimitReachedTitle': 'Daily limit reached',
      'dailyLimitReachedMessage':
          'You reached your free daily limit. Upgrade to Premium for unlimited downloads.',
      'freeDownloadsLeft': 'Free downloads left today: {count}/5',
      'adPlaceholderTitle': 'Ad Placeholder',
      'adPlaceholderMessage': 'This is where an ad will appear for free users.',
      'premiumActivatedSuccess': 'Premium activated successfully.',
      'premiumMonthly': 'Premium Monthly',
      'premiumYearly': 'Premium Yearly',
      'premiumLifetime': 'Premium Lifetime',
      'fhd4kPremiumTitle': 'FHD & 4K downloads are Premium.',
      'fhd4kPremiumMessage':
          'Upgrade to download in higher quality when available.',
      'batchPremiumTitle': 'Batch downloads are Premium.',
      'batchPremiumMessage': 'Upgrade to download multiple links together.',
      'audioExtractionPremiumTitle': 'Audio extraction is Premium.',
      'audioExtractionPremiumMessage':
          'Upgrade to extract audio from your media links.',
      'noWatermarkPremiumTitle': 'No watermark downloads are Premium.',
      'noWatermarkPremiumMessage':
          'Available when the platform provides a no-watermark version.',
      'audioSwapPremiumTitle': 'Audio Swap is a Premium feature.',
      'audioSwapPremiumMessage':
          'Upgrade to replace the original video sound with your own audio.',
      'audioSwap': 'Audio Swap',
      'audioSwapReplaceAudio': 'Audio Swap / Replace Audio',
      'replaceAudio': 'Replace Audio',
      'audioSwapSubtitle': 'Replace original audio with your own sound.',
      'audioSwapDescription':
          'Replace the original video sound with an audio file from your phone.',
      'pickAudioFile': 'Pick Audio File',
      'selectedAudio': 'Selected audio',
      'audioFormatSupport': 'MP3 / M4A / WAV supported later',
      'audioStartPosition': 'Audio start position in video',
      'removeOriginalSound': 'Remove original sound',
      'keepOriginalSoundSoftly': 'Keep original sound softly',
      'audioVolume': 'Audio volume',
      'preview': 'Preview',
      'applyAudioSwap': 'Apply Audio Swap',
      'audioReplacedSuccess': 'Audio replaced successfully',
      'noAudioSelected': 'Pick an audio file first.',
      'demoPreviewReady': 'Demo preview is ready.',
      'somethingWentWrong': 'Something went wrong. Please try again.',
      'demoActionForNow': '{action} is a demo action for now.',
      'shareDemoAction': 'Share is a demo action for now.',
      'openDemoAction': 'Open is a demo action for now.',
      'saveGalleryDemoAction': 'Save to gallery is a demo action for now.',
      'demoExtractionPrepared': 'Demo {format} extraction prepared.',
      'batchQueueCreated': 'Demo queue created. Backend will run this later.',
      'batchLimitExceeded': 'You can download up to 5 links at a time.',
      'notAvailableOnClip': 'Not available on this clip',
      'notAvailableForImage': 'Not available for this image',
      'Instagram photo posts are not available for this link. Try a Reel/video link.':
          'Instagram photo posts are not available for this link. Try a Reel/video link.',
      'noWatermarkApplied': 'No watermark applied when available',
      'downloadSelected': 'Download selected',
      'downloadSelectedItems': 'Download selected items',
      'downloadSelectedItemsCount': 'Download {count} selected items',
      'selectedItemsDownloaded': 'Selected items downloaded successfully',
      'chooseImageFormat': 'Choose image format',
      'originalImage': 'Original Image',
      'highQualityImage': 'High Quality Image',
      'compressedImage': 'Compressed Image',
      'jpgImage': 'JPG Image',
      'pngImage': 'PNG Image',
      'bestAvailableQuality': 'Best available quality',
      'premiumQualityWhenAvailable': 'Premium quality when available',
      'smallerFileSize': 'Smaller file size',
      'standardFormat': 'Standard format',
      'whenAvailable': 'When available',
      'imagePremiumTitle': 'High quality images are Premium.',
      'imagePremiumMessage':
          'Upgrade to download premium image formats when available.',
      'yourApexLoad': 'Your ApexLoad',
      'appStatus': 'App Status',
      'plan': 'Plan',
      'downloadsToday': 'Downloads today',
      'storageUsed': 'Storage used',
      'locked': 'Locked',
      'unlocked': 'Unlocked',
      'free': 'Free',
      'all': 'All',
      'video': 'Video',
      'audio': 'Audio',
      'images': 'Images',
      'open': 'Open',
      'share': 'Share',
      'edit': 'Edit',
      'rename': 'Rename',
      'delete': 'Delete',
      'goHome': 'Go Home',
      'pasteOneLinkPerLine': 'Paste one public link per line',
      'queuePreview': 'Queue preview',
      'startBatchDownload': 'Start batch download',
      'ready': 'Ready',
      'invalidLink': 'Invalid link',
      'pasteMediaLink': 'Paste media link',
      'audioFormat': 'Audio format',
      'audioQuality': 'Audio quality',
      'systemDefault': 'System Default',
      'english': 'English',
      'arabic': 'Arabic',
      'system': 'System',
      'dark': 'Dark',
      'light': 'Light',
      'autoSaveToGallery': 'Auto-save to gallery',
      'downloadLocation': 'Download location',
      'deviceDownloadsFolder': 'Device downloads folder',
      'clearCache': 'Clear cache',
      'demoCacheOnly': 'Demo cache only',
      'privacyPolicy': 'Privacy Policy',
      'termsOfUse': 'Terms of Use',
      'contactSupport': 'Contact Support',
      'rateApp': 'Rate App',
      'placeholder': 'Placeholder',
      'comingSoon': 'Coming soon',
      'madeBy': 'Made by',
    },
    'ar': {
      'home': 'الرئيسية',
      'downloads': 'التحميلات',
      'batch': 'الدفعات',
      'settings': 'الإعدادات',
      'skip': 'تخطي',
      'continue': 'متابعة',
      'getStarted': 'ابدأ الآن',
      'onboardingTitle1': 'الصق أي رابط وسائط مدعوم',
      'onboardingDesc1': 'انسخ رابط فيديو عام من منصتك المفضلة والصقه هنا.',
      'onboardingTitle2': 'اختر الصيغة المناسبة',
      'onboardingDesc2':
          'نزّل الفيديو، استخرج الصوت، احفظ الصورة المصغّرة، والمزيد.',
      'onboardingTitle3': 'فعّل بريميوم لقوة أكبر',
      'onboardingDesc3':
          'افتح جودة FHD و 4K عند توفرها، وبدون علامة مائية عند توفرها، والدفعات، والمحرر السريع، وتبديل الصوت، والطابور الأسرع، وتجربة بدون إعلانات.',
      'pasteYourVideoLink': 'الصق رابط الفيديو',
      'analyzeLink': 'تحليل الرابط',
      'downloadCompleted': 'اكتمل التحميل',
      'analyzeFailed': 'تعذر تحليل الرابط، حاول مرة أخرى',
      'backendUnavailableDemo':
          'الخادم غير متاح حالياً، سيتم عرض نتيجة تجريبية',
      'downloadJobCreated': 'تم إنشاء مهمة التحميل',
      'downloadJobFailed': 'تعذر إنشاء مهمة التحميل، حاول مرة أخرى',
      'downloadFailed': 'فشل التحميل. جرّب صيغة أو رابطًا آخر.',
      'downloadFailedNoFiles': 'اكتمل التحميل، لكن لم يتم إرجاع أي ملفات.',
      'noMediaToShow': 'لا توجد وسائط للعرض',
      'analyzeFirstForOptions':
          'الصق رابطًا وحلّله أولًا لاختيار خيارات التحميل.',
      'noDownloadInProgress': 'لا يوجد تحميل قيد التقدم',
      'startDownloadFirst': 'ابدأ التحميل من شاشة الخيارات أولًا.',
      'noVideoSelected': 'لم يتم اختيار فيديو',
      'openQuickEditorFirst': 'افتح المحرر السريع من فيديو تم تحميله أولًا.',
      'instagramBlocked':
          'حظر Instagram هذا الطلب. حدّث ملفات تعريف الارتباط وجرب مرة أخرى.',
      'connectionProblem': 'مشكلة في الاتصال. حاول مرة أخرى.',
      'queued': 'في الانتظار',
      'downloading': 'جاري التنزيل',
      'readyToOpen': 'جاهز للفتح',
      'selectDownloadOption': 'اختر خيار تنزيل واحداً على الأقل',
      'upgradeToPremium': 'الترقية إلى بريميوم',
      'premium': 'بريميوم',
      'premiumRequired': 'بريميوم مطلوب',
      'legalShort': 'حمّل فقط المحتوى الذي تملكه أو لديك إذن باستخدامه.',
      'legalFull':
          'هذا التطبيق مخصص فقط لتحميل المحتوى الذي تملكه، أو لديك إذن لاستخدامه، أو المحتوى المسموح بتحميله بشكل عام. أنت مسؤول عن احترام حقوق النشر وشروط المنصات.',
      'supportedPlatforms': 'المنصات المدعومة',
      'recentDownloads': 'آخر التحميلات',
      'viewAll': 'عرض الكل',
      'pasteFirst': 'الصق رابط وسائط عام أولاً.',
      'clipboardEmpty': 'الحافظة فارغة الآن.',
      'premiumActive': 'الاشتراك المميز نشط',
      'active': 'مفعّل',
      'freePlan': 'الخطة المجانية',
      'noWatermarkDownloads': 'تحميلات بدون علامة مائية',
      'noWatermarkWhenAvailable': 'بدون علامة مائية عند توفرها',
      'homeUpgradeCopy':
          'احصل على بريميوم لتحميل بجودة FHD و 4K عند توفرها، وبدون إعلانات، والدفعات، والمحرر السريع، وتبديل الصوت، و',
      'fhd4kDownloads': 'تحميل بجودة FHD و 4K عند توفرها',
      'fhd4kDownloadsWhenAvailable': 'حمّل بجودة FHD و 4K عند توفرها.',
      'fhd4kExport': 'تصدير بجودة FHD و 4K',
      'fhd4kShort': 'FHD و 4K',
      'unlockFhd4kQuality': 'افتح جودة FHD و 4K عند توفرها',
      'monthly': 'شهري',
      'yearly': 'سنوي',
      'lifetime': 'مدى الحياة',
      'monthlyPrice': '0.99 دولار / شهرياً',
      'yearlyPrice': '9.99 دولار / سنوياً',
      'lifetimePrice': '24.99 دولار مرة واحدة',
      'import': 'استيراد',
      'validate': 'تحقق',
      'language': 'اللغة',
      'theme': 'المظهر',
      'quickEditor': 'المحرر السريع',
      'quickEditorSubtitle':
          'قص الفيديو، كتم الصوت، استخراج الصوت، وضغط الفيديو.',
      'quickEditorPremiumTitle': 'المحرر السريع ميزة بريميوم',
      'quickEditorPremiumMessage':
          'قم بالترقية لقص الفيديو، كتم الصوت، استخراج الصوت، استبدال الصوت، وضغط الفيديو',
      'editVideo': 'تعديل الفيديو',
      'trimVideo': 'قص الفيديو',
      'muteVideo': 'كتم الصوت',
      'extractAudio': 'استخراج الصوت',
      'compressVideo': 'ضغط الفيديو',
      'exportEditedVideo': 'تصدير الفيديو المعدل',
      'format': 'الصيغة',
      'startTime': 'وقت البداية',
      'endTime': 'وقت النهاية',
      'trimDuration': 'مدة القص',
      'seconds': 'ثواني',
      'applyTrim': 'تطبيق القص',
      'removeOriginalAudio': 'إزالة الصوت الأصلي',
      'applyMute': 'تطبيق الكتم',
      'standard': 'عادي',
      'high': 'عالي',
      'smallFile': 'ملف صغير',
      'balanced': 'متوازن',
      'highQuality': 'جودة عالية',
      'highestQuality': 'أعلى جودة',
      'estimatedReduction': 'تقليل الحجم المتوقع: أصغر بنسبة 35%',
      'compress': 'ضغط',
      'exportSettings': 'إعدادات التصدير',
      'saveToGallery': 'حفظ في المعرض',
      'noWatermarkNote': 'تطبق فقط عندما توفرها المنصة أو المصدر.',
      'processingLocally': 'تتم المعالجة محلياً على هذا الجهاز',
      'trimSuccess': 'تم تطبيق القص بنجاح',
      'muteSuccess': 'تم كتم الفيديو بنجاح',
      'audioExtractedSuccess': 'تم استخراج الصوت بنجاح',
      'compressSuccess': 'تم ضغط الفيديو بنجاح',
      'exportSuccess': 'تم تصدير الفيديو المعدل بنجاح',
      'quickEditorBenefit':
          'قص الفيديو، كتم الصوت، استخراج الصوت، وضغط الفيديو.',
      'platformTikTok': 'تيك توك',
      'platformInstagram': 'إنستغرام',
      'platformFacebook': 'فيسبوك',
      'platformXTwitter': 'إكس/تويتر',
      'platformYouTubeShorts': 'يوتيوب شورتس',
      'platformPinterest': 'بنترست',
      'platformReddit': 'ريديت',
      'platformSnapchat': 'سناب شات',
      'unlockPremiumTitle': 'افتح ApexLoad بريميوم',
      'premiumSubtitle': 'سرعة أكثر. جودة أعلى. بدون حدود.',
      'noAds': 'بدون إعلانات',
      'batchDownloads': 'تحميل الدفعات',
      'audioExtraction': 'استخراج الصوت',
      'fasterQueue': 'طابور أسرع',
      'unlimitedDownloads': 'تحميلات غير محدودة',
      'cloudSave': 'حفظ سحابي',
      'bestValue': 'أفضل قيمة',
      'premiumActivatedDemo': 'تم تفعيل بريميوم في النسخة التجريبية.',
      'premiumActiveButton': 'الاشتراك المميز نشط',
      'termsPrivacyPlaceholder':
          'الشروط والخصوصية عناصر مؤقتة في نسخة الواجهة الحالية.',
      'downloadOptions': 'خيارات التحميل',
      'chooseFormat': 'اختر الصيغة',
      'customFilename': 'اسم الملف المخصص',
      'download': 'تحميل',
      'openAudioTool': 'فتح أداة استخراج الصوت',
      'viewPremium': 'عرض بريميوم',
      'premiumOption': 'خيار بريميوم',
      'premiumFeatureSummary':
          'افتح جودة FHD و 4K عند توفرها، وبدون علامة مائية عند توفرها، والمحرر السريع، واستخراج الصوت، وتحميل الدفعات.',
      'downloadProgress': 'تقدم التحميل',
      'openLibrary': 'فتح المكتبة',
      'downloadAnother': 'تحميل رابط آخر',
      'cancel': 'إلغاء',
      'platform': 'المنصة',
      'speed': 'السرعة',
      'queuePosition': 'ترتيب الطابور',
      'savedLocally': 'تم الحفظ محلياً',
      'done': 'تم',
      'searchDownloads': 'البحث في التحميلات',
      'noDownloadsYet': 'لا توجد تحميلات بعد',
      'pasteLinkOnHome': 'الصق رابطاً في الشاشة الرئيسية للبدء.',
      'renameFile': 'إعادة تسمية الملف',
      'filename': 'اسم الملف',
      'save': 'حفظ',
      'upgradeNow': 'الترقية الآن',
      'maybeLater': 'ربما لاحقاً',
      'dailyLimitReachedTitle': 'تم الوصول إلى الحد اليومي',
      'dailyLimitReachedMessage':
          'لقد وصلت إلى الحد اليومي المجاني. قم بالترقية إلى بريميوم لتحميلات غير محدودة.',
      'freeDownloadsLeft': 'التحميلات المجانية المتبقية اليوم: {count}/5',
      'adPlaceholderTitle': 'إعلان تجريبي',
      'adPlaceholderMessage': 'هنا سيظهر الإعلان للمستخدمين المجانيين',
      'premiumActivatedSuccess': 'تم تفعيل بريميوم بنجاح.',
      'premiumMonthly': 'بريميوم شهري',
      'premiumYearly': 'بريميوم سنوي',
      'premiumLifetime': 'بريميوم مدى الحياة',
      'fhd4kPremiumTitle': 'تحميلات FHD و 4K ميزة بريميوم.',
      'fhd4kPremiumMessage': 'قم بالترقية للتحميل بجودة أعلى عند توفرها.',
      'batchPremiumTitle': 'تحميل الدفعات ميزة بريميوم.',
      'batchPremiumMessage': 'قم بالترقية لتحميل عدة روابط معاً.',
      'audioExtractionPremiumTitle': 'استخراج الصوت ميزة بريميوم.',
      'audioExtractionPremiumMessage':
          'قم بالترقية لاستخراج الصوت من روابط الوسائط.',
      'noWatermarkPremiumTitle': 'التحميل بدون علامة مائية ميزة بريميوم.',
      'noWatermarkPremiumMessage':
          'متاح عندما توفر المنصة نسخة بدون علامة مائية.',
      'audioSwapPremiumTitle': 'تبديل الصوت ميزة بريميوم.',
      'audioSwapPremiumMessage':
          'قم بالترقية لاستبدال صوت الفيديو الأصلي بصوت من جهازك.',
      'audioSwap': 'تبديل الصوت',
      'audioSwapReplaceAudio': 'تبديل الصوت / استبدال الصوت',
      'replaceAudio': 'استبدال الصوت',
      'audioSwapSubtitle': 'استبدل صوت الفيديو الأصلي بصوت من جهازك',
      'audioSwapDescription': 'استبدل صوت الفيديو الأصلي بملف صوتي من هاتفك.',
      'pickAudioFile': 'اختيار ملف صوتي',
      'selectedAudio': 'الصوت المختار',
      'audioFormatSupport': 'سيتم دعم MP3 / M4A / WAV لاحقاً',
      'audioStartPosition': 'بداية الصوت داخل الفيديو',
      'removeOriginalSound': 'إزالة الصوت الأصلي',
      'keepOriginalSoundSoftly': 'إبقاء الصوت الأصلي منخفض',
      'audioVolume': 'مستوى الصوت',
      'preview': 'معاينة',
      'applyAudioSwap': 'تطبيق تبديل الصوت',
      'audioReplacedSuccess': 'تم استبدال الصوت بنجاح',
      'noAudioSelected': 'اختر ملفاً صوتياً أولاً.',
      'demoPreviewReady': 'المعاينة التجريبية جاهزة.',
      'somethingWentWrong': 'حدث خطأ، حاول مرة أخرى',
      'demoActionForNow': '{action} حالياً مجرد تجربة',
      'shareDemoAction': 'المشاركة حالياً مجرد تجربة',
      'openDemoAction': 'الفتح حالياً مجرد تجربة',
      'saveGalleryDemoAction': 'الحفظ في المعرض حالياً مجرد تجربة',
      'demoExtractionPrepared': 'تم تجهيز استخراج {format} كتجربة.',
      'batchQueueCreated':
          'تم إنشاء قائمة تجريبية. سيتم تشغيلها من الخادم لاحقاً.',
      'batchLimitExceeded': 'يمكنك تحميل ما يصل إلى 5 روابط في كل مرة.',
      'notAvailableOnClip': 'غير متوفر لهذا المقطع',
      'notAvailableForImage': 'غير متوفر لهذه الصورة',
      'Instagram photo posts are not available for this link. Try a Reel/video link.':
          'منشورات الصور في إنستغرام غير متاحة لهذا الرابط. جرّب رابط Reel أو فيديو.',
      'noWatermarkApplied': 'سيتم التحميل بدون علامة مائية عند توفر ذلك',
      'downloadSelected': 'تحميل المحدد',
      'downloadSelectedItems': 'تحميل العناصر المحددة',
      'downloadSelectedItemsCount': 'تحميل {count} عناصر محددة',
      'selectedItemsDownloaded': 'تم تحميل العناصر المحددة بنجاح',
      'chooseImageFormat': 'اختر صيغة الصورة',
      'originalImage': 'الصورة الأصلية',
      'highQualityImage': 'صورة عالية الجودة',
      'compressedImage': 'صورة مضغوطة',
      'jpgImage': 'صورة JPG',
      'pngImage': 'صورة PNG',
      'bestAvailableQuality': 'أفضل جودة متاحة',
      'premiumQualityWhenAvailable': 'جودة بريميوم عند توفرها',
      'smallerFileSize': 'حجم ملف أصغر',
      'standardFormat': 'صيغة قياسية',
      'whenAvailable': 'عند توفرها',
      'imagePremiumTitle': 'الصور عالية الجودة ميزة بريميوم.',
      'imagePremiumMessage': 'قم بالترقية لتحميل صيغ الصور المميزة عند توفرها.',
      'yourApexLoad': 'حساب ApexLoad الخاص بك',
      'appStatus': 'حالة التطبيق',
      'plan': 'الخطة',
      'downloadsToday': 'تحميلات اليوم',
      'storageUsed': 'المساحة المستخدمة',
      'locked': 'مقفل',
      'unlocked': 'مفتوح',
      'free': 'مجاني',
      'all': 'الكل',
      'video': 'فيديو',
      'audio': 'صوت',
      'images': 'صور',
      'open': 'فتح',
      'share': 'مشاركة',
      'edit': 'تعديل',
      'rename': 'إعادة تسمية',
      'delete': 'حذف',
      'goHome': 'العودة للرئيسية',
      'pasteOneLinkPerLine': 'الصق رابطاً عاماً في كل سطر',
      'queuePreview': 'معاينة القائمة',
      'startBatchDownload': 'بدء تحميل الدفعة',
      'ready': 'جاهز',
      'invalidLink': 'رابط غير صالح',
      'pasteMediaLink': 'الصق رابط الوسائط',
      'audioFormat': 'صيغة الصوت',
      'audioQuality': 'جودة الصوت',
      'systemDefault': 'افتراضي النظام',
      'english': 'English',
      'arabic': 'العربية',
      'system': 'النظام',
      'dark': 'داكن',
      'light': 'فاتح',
      'autoSaveToGallery': 'الحفظ التلقائي في المعرض',
      'downloadLocation': 'مكان التحميل',
      'deviceDownloadsFolder': 'مجلد التحميلات على الجهاز',
      'clearCache': 'مسح الذاكرة المؤقتة',
      'demoCacheOnly': 'ذاكرة تجريبية فقط',
      'privacyPolicy': 'سياسة الخصوصية',
      'termsOfUse': 'شروط الاستخدام',
      'contactSupport': 'التواصل مع الدعم',
      'rateApp': 'تقييم التطبيق',
      'placeholder': 'عنصر مؤقت',
      'comingSoon': 'قريباً',
      'madeBy': 'صنع بواسطة',
    },
  };

  String t(String key) =>
      _values[locale.languageCode]?[key] ?? _values['en']![key] ?? key;

  String platformName(String name) {
    return switch (name) {
      'TikTok' => t('platformTikTok'),
      'Instagram' => t('platformInstagram'),
      'Facebook' => t('platformFacebook'),
      'X/Twitter' => t('platformXTwitter'),
      'YouTube Shorts' => t('platformYouTubeShorts'),
      'Pinterest' => t('platformPinterest'),
      'Reddit' => t('platformReddit'),
      'Snapchat' => t('platformSnapchat'),
      _ => name,
    };
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
